# Generated by Django 2.2.24 on 2023-05-25 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20230525_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_services', to='bot.Service'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_specialist', to='bot.Specialist'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_user', to='bot.User', verbose_name='Имя клиента'),
        ),
    ]
