# Generated by Django 2.2.24 on 2023-05-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_work_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
            ],
        ),
    ]
