# Generated by Django 2.2.24 on 2023-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20230527_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Запись клиента', 'verbose_name_plural': 'Записи клиентов'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Оплаченная сумма'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='Оплата проведена?'),
        ),
    ]
